stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

unittest-lock:
  stage: test
  image: python:latest
  cache:
    paths:
      - locks/pico/.venv/

  before_script:
    - cd locks/pico
    - python3 --version ; pip3 --version  # For debugging
    - pip3 install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

  script:
    - pip3 install -r requirements.txt
    - python3 -m coverage run --source=src -m unittest discover

  after_script:
    - cd locks/pico
    - source .venv/bin/activate
    - python3 -m coverage report
    - python3 -m coverage html

  artifacts:
    expire_in: 7 days
    name: coverage_report
    paths:
      - locks/pico/htmlcov
